name: Keep Railway Alive

on:
  schedule:
    - cron: "*/4 * * * *" # every 4 minutes (UTC)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit the users API
        run: curl -s https://hydro-secrete-production.up.railway.app/api/utils/locations
